apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "6.2.2"
  test:
    enable: false
  values:

#   image:
#     repository: ghcr.io/stefanprodan/podinfo
#     tag: 6.2.2
#     pullPolicy: IfNotPresent

    ingress:
      hosts:
        - host: podinfo.dmz-infra
          paths:
            - path: /
              pathType: ImplementationSpecific
# containers:
#   image: ghcr.io/stefanprodan/podinfo:6.2.2
#   image:
#     tag: 2.9.9
